name: Release module
on:
  push:
    tags: ['*'] # semver format

permissions:
  contents: read # needed for checkout
  packages: write # needed for GHCR access

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Lint
        run: |
          timoni mod lint . --debug
      - name: Test instance build
        run: |
          timoni build -n testing test . --values debug_values.cue
      - name: Push
        run: |
          timoni mod push . \
            oci://ghcr.io/${{ github.repository }} \
            --version ${{ github.ref_name }} \
            --creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            --latest \
            -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}'
